import { createContext, useContext, useMemo, useState } from "react";

const LANGUAGE_STORAGE_KEY = "sc_language";

const translations = {
  en: {
    language: "Language",
    english: "English",
    telugu: "తెలుగు",
    hindi: "हिन्दी",
    home: "Home",
    myComplaints: "My Complaints",
    about: "About",
    reportIssue: "Report Issue",
    admin: "Admin",
    adminWorkspace: "Admin workspace",
    login: "Log In",
    signUp: "Sign Up",
    logout: "Sign Out",
    appearance: "Appearance",
    light: "Light",
    dark: "Dark",
    accountMenu: "Account menu",
    locationNotSet: "Location not set",
    reportComplaint: "Report Complaint",
    newComplaint: "New Complaint",
    assistant: "AI Assistant",
    askAi: "Ask AI",
    close: "Close",
    totalFiled: "Total Filed",
    inProgress: "In Progress",
    resolved: "Resolved",
    pending: "Pending",
    all: "All",
    searchComplaints: "Search by title, category, ID...",
    newest: "Newest First",
    oldest: "Oldest First",
    priority: "By Priority",
    noComplaints: "No complaints found",
    adjustSearch: "Try adjusting your search or filter.",
    viewDetails: "View Details",
    filed: "Filed",
    updated: "Updated",
    welcomeBack: "Welcome back",
    signedInAs: "You're signed in as",
    noAccount: "Don't have an account yet?",
    registerTrack: "Register for free to report issues and track resolutions.",
    createFreeAccount: "Create Free Account",
    smartCityInitiative: "Smart City Initiative",
    yourCity: "Your City,",
    yourVoice: "Your Voice.",
    heroDescription: "Report public issues, track resolutions in real-time, and help authorities build a better city-all in one place.",
    reportAnIssue: "Report an Issue",
    signInGetStarted: "Sign In to Get Started",
    everythingYouNeed: "Everything You Need",
    howItWorks: "How It Works",
    recentActivity: "Recent Activity",
    spottedProblem: "Spotted a problem in your city?",
    getStarted: "Get Started",
    citizenPortal: "Citizen Portal",
    trackReported: "Track the status of your reported issues in real-time.",
    title: "Title",
    description: "Description",
    location: "Location",
    submitComplaint: "Submit Complaint",
    fullName: "Full Name",
    clearForm: "Clear Form",
  },
  te: {
    language: "భాష",
    english: "English",
    telugu: "తెలుగు",
    hindi: "हिन्दी",
    home: "హోమ్",
    myComplaints: "నా ఫిర్యాదులు",
    about: "గురించి",
    reportIssue: "సమస్యను నివేదించండి",
    admin: "అడ్మిన్",
    adminWorkspace: "అడ్మిన్ వర్క్‌స్పేస్",
    login: "లాగిన్",
    signUp: "సైన్ అప్",
    logout: "సైన్ అవుట్",
    appearance: "రూపం",
    light: "లైట్",
    dark: "డార్క్",
    accountMenu: "ఖాతా మెను",
    locationNotSet: "స్థానం సెట్ కాలేదు",
    reportComplaint: "ఫిర్యాదును నివేదించండి",
    newComplaint: "కొత్త ఫిర్యాదు",
    assistant: "AI సహాయకుడు",
    askAi: "AI ని అడగండి",
    close: "మూసివేయి",
    totalFiled: "మొత్తం నమోదు",
    inProgress: "పురోగతిలో ఉంది",
    resolved: "పరిష్కరించబడింది",
    pending: "పెండింగ్‌లో ఉంది",
    all: "అన్నీ",
    searchComplaints: "శీర్షిక, వర్గం, ID ద్వారా వెతకండి...",
    newest: "కొత్తవి ముందు",
    oldest: "పాతవి ముందు",
    priority: "ప్రాధాన్యత ప్రకారం",
    noComplaints: "ఫిర్యాదులు కనుగొనబడలేదు",
    adjustSearch: "మీ శోధన లేదా ఫిల్టర్‌ను మార్చి ప్రయత్నించండి.",
    viewDetails: "వివరాలు చూడండి",
    filed: "నమోదు",
    updated: "నవీకరణ",
    welcomeBack: "తిరిగి స్వాగతం",
    signedInAs: "మీరు సైన్ ఇన్ చేసిన ఖాతా",
    noAccount: "ఇంకా ఖాతా లేదా?",
    registerTrack: "సమస్యలను నివేదించడానికి మరియు పరిష్కారాలను ట్రాక్ చేయడానికి ఉచితంగా నమోదు చేసుకోండి.",
    createFreeAccount: "ఉచిత ఖాతా సృష్టించండి",
    smartCityInitiative: "స్మార్ట్ సిటీ కార్యక్రమం",
    yourCity: "మీ నగరం,",
    yourVoice: "మీ గొంతు.",
    heroDescription: "ప్రజా సమస్యలను నివేదించి, పరిష్కారాలను నిజ సమయంలో ట్రాక్ చేసి, మెరుగైన నగర నిర్మాణానికి సహాయపడండి.",
    reportAnIssue: "సమస్యను నివేదించండి",
    signInGetStarted: "ప్రారంభించడానికి సైన్ ఇన్ చేయండి",
    everythingYouNeed: "మీకు కావలసినవన్నీ",
    howItWorks: "ఇది ఎలా పనిచేస్తుంది",
    recentActivity: "ఇటీవలి కార్యకలాపాలు",
    spottedProblem: "మీ నగరంలో సమస్య కనిపించిందా?",
    getStarted: "ప్రారంభించండి",
    citizenPortal: "పౌర పోర్టల్",
    trackReported: "మీరు నివేదించిన సమస్యల స్థితిని నిజ సమయంలో ట్రాక్ చేయండి.",
    title: "శీర్షిక",
    description: "వివరణ",
    location: "స్థానం",
    submitComplaint: "ఫిర్యాదును సమర్పించండి",
    fullName: "పూర్తి పేరు",
    clearForm: "ఫారమ్‌ను క్లియర్ చేయండి",
  },
  hi: {
    language: "भाषा",
    english: "English",
    telugu: "తెలుగు",
    hindi: "हिन्दी",
    home: "होम",
    myComplaints: "मेरी शिकायतें",
    about: "परिचय",
    reportIssue: "समस्या दर्ज करें",
    admin: "एडमिन",
    adminWorkspace: "एडमिन कार्यक्षेत्र",
    login: "लॉग इन",
    signUp: "साइन अप",
    logout: "साइन आउट",
    appearance: "दिखावट",
    light: "लाइट",
    dark: "डार्क",
    accountMenu: "खाता मेनू",
    locationNotSet: "स्थान सेट नहीं है",
    reportComplaint: "शिकायत दर्ज करें",
    newComplaint: "नई शिकायत",
    assistant: "AI सहायक",
    askAi: "AI से पूछें",
    close: "बंद करें",
    totalFiled: "कुल दर्ज",
    inProgress: "प्रगति में",
    resolved: "हल की गई",
    pending: "लंबित",
    all: "सभी",
    searchComplaints: "शीर्षक, श्रेणी या ID से खोजें...",
    newest: "नवीनतम पहले",
    oldest: "सबसे पुरानी पहले",
    priority: "प्राथमिकता के अनुसार",
    noComplaints: "कोई शिकायत नहीं मिली",
    adjustSearch: "अपनी खोज या फ़िल्टर बदलकर देखें।",
    viewDetails: "विवरण देखें",
    filed: "दर्ज",
    updated: "अपडेट",
    welcomeBack: "वापसी पर स्वागत है",
    signedInAs: "आप साइन इन हैं",
    noAccount: "अभी तक खाता नहीं है?",
    registerTrack: "समस्याएं दर्ज करने और समाधान ट्रैक करने के लिए निःशुल्क पंजीकरण करें।",
    createFreeAccount: "निःशुल्क खाता बनाएं",
    smartCityInitiative: "स्मार्ट सिटी पहल",
    yourCity: "आपका शहर,",
    yourVoice: "आपकी आवाज़।",
    heroDescription: "सार्वजनिक समस्याएं दर्ज करें, समाधान ट्रैक करें और बेहतर शहर बनाने में मदद करें।",
    reportAnIssue: "समस्या दर्ज करें",
    signInGetStarted: "शुरू करने के लिए लॉग इन करें",
    everythingYouNeed: "आपको सब कुछ चाहिए",
    howItWorks: "यह कैसे काम करता है",
    recentActivity: "हाल की गतिविधि",
    spottedProblem: "अपने शहर में कोई समस्या देखी?",
    getStarted: "शुरू करें",
    citizenPortal: "नागरिक पोर्टल",
    trackReported: "अपनी दर्ज की गई समस्याओं की स्थिति रियल टाइम में ट्रैक करें।",
    title: "शीर्षक",
    description: "विवरण",
    location: "स्थान",
    submitComplaint: "शिकायत दर्ज करें",
    fullName: "पूरा नाम",
    clearForm: "फ़ॉर्म साफ़ करें",
  },
};

const getInitialLanguage = () => {
  const savedLanguage = localStorage.getItem(LANGUAGE_STORAGE_KEY);
  return translations[savedLanguage] ? savedLanguage : "en";
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState(getInitialLanguage);

  const setLanguage = (nextLanguage) => {
    if (!translations[nextLanguage]) return;
    localStorage.setItem(LANGUAGE_STORAGE_KEY, nextLanguage);
    setLanguageState(nextLanguage);
  };

  const value = useMemo(
    () => ({
      language,
      setLanguage,
      translations: translations[language],
      t: (key) => translations[language][key] || translations.en[key] || key,
    }),
    [language]
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used inside LanguageProvider");
  return context;
}

export const LANGUAGE_OPTIONS = [
  { value: "en", label: "English" },
  { value: "te", label: "తెలుగు" },
  { value: "hi", label: "हिन्दी" },
];
